// The full Situational Quiz bank: 10 scenarios x 4 modules x 3 tiers = 120.
// Every entry follows the Section 4A template: A = reactive/avoidant,
// B = technically correct but socially clumsy, C = best-practice (always
// correct, per the template), D = overcorrection that breaks standard/timing.

export type ScenarioTier = "QSR" | "CASUAL" | "FINE_DINING";

export type ScenarioSeed = {
  moduleNumber: number;
  tier: ScenarioTier;
  situation: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: "C";
  skillTested: string;
  coachingNote: string;
};

type Row = [
  situation: string,
  optionA: string,
  optionB: string,
  optionC: string,
  optionD: string,
  coachingNote: string
];

function build(
  moduleNumber: number,
  tier: ScenarioTier,
  skillTested: string,
  rows: Row[]
): ScenarioSeed[] {
  return rows.map(
    ([situation, optionA, optionB, optionC, optionD, coachingNote]) => ({
      moduleNumber,
      tier,
      situation,
      optionA,
      optionB,
      optionC,
      optionD,
      correctAnswer: "C" as const,
      skillTested,
      coachingNote,
    })
  );
}

// ---------------------------------------------------------------------------
// MODULE 1 — THE GUEST READ (Emotional Intelligence · Empathy · Active Listening)
// ---------------------------------------------------------------------------

const M1_QSR: Row[] = [
  [
    "You're mid-rush at the front counter. A guest is juggling two kids and a tray, clearly overwhelmed, scanning the menu board with a growing line behind them.",
    "Wait for them to speak first, keep the line moving as usual",
    "Point at the menu board and tell them to take their time",
    "Make eye contact, offer a quick suggestion to simplify their choice, and help them get through the line faster",
    "Call a manager over to handle the guest personally",
    "A fast, kind assist reads the overwhelmed-parent cue and removes friction without slowing the line. If you picked A, watch for guests visibly struggling next shift — silence isn't neutral, it's a missed read.",
  ],
  [
    "A regular who always orders the same thing steps up looking distracted and orders something completely different without explanation.",
    "Ring it up exactly as said, no comment",
    "Ask 'are you sure?' in a way that puts them on the spot",
    "Ring it up, and casually mention you noticed they switched it up today — open the door if they want to talk",
    "Assume it's a mistake and correct it to their usual order",
    "Naming the change (without prying) shows you actually see them as a person, not a transaction. If you picked D, watch for that instinct next shift — assuming you know better than the guest erodes trust fast.",
  ],
  [
    "A guest reading the menu board mouths the same three items over and over, clearly torn, while three people wait behind them.",
    "Let them keep deciding, it's their choice",
    "Tell them to step aside and decide, then come back",
    "Offer a quick, specific recommendation based on what they seem drawn to, so they can decide fast",
    "Pick for them and ring it up before they can object",
    "A confident nudge respects their time and the line's. If you picked A, watch for that stall next shift — silence in the face of visible hesitation reads as indifference, not patience.",
  ],
  [
    "An elderly guest is squinting at the digital menu board and hasn't moved up in line for several seconds.",
    "Wait for them to ask for help",
    "Raise your voice and repeat the menu items faster",
    "Step toward them, offer a printed menu or read the board's options aloud, unprompted",
    "Skip to the next guest and come back to them later",
    "Reading the struggle before it becomes a request is the whole skill. If you picked D, watch for that shortcut next shift — skipping a guest to save time usually costs more time in embarrassment and delay.",
  ],
  [
    "A guest orders quickly, avoids eye contact, and taps their foot while waiting — clearly in a hurry.",
    "Proceed at your normal pace, rushing isn't your job",
    "Comment on how busy they seem to make conversation",
    "Move with visibly quicker pace and mention their order is being prioritized",
    "Apologize repeatedly for the wait even though nothing's gone wrong yet",
    "Matching their urgency without being told is the read. If you picked B, watch for that next shift — narrating a guest's mood back to them can feel like commentary, not service.",
  ],
  [
    "A group of teenagers orders separately but is clearly together, giggling and unsure of register etiquette.",
    "Treat each order as fully separate with no acknowledgment",
    "Lecture them on ordering together next time",
    "Acknowledge they're a group with a friendly tone and help them combine or separate payment smoothly",
    "Rush them through to discourage the group ordering pattern",
    "A friendly, competent assist turns first-time confusion into a good first impression. If you picked D, watch for that instinct — impatience with unfamiliarity reads as rudeness, not efficiency.",
  ],
  [
    "A guest's card is declined and their face flushes with embarrassment as the line watches.",
    "Announce the decline loudly so they can try another card",
    "Say nothing and just wait for them to figure it out",
    "Lower your voice, quietly suggest another payment method, and keep the moment low-key",
    "Offer to comp the order to avoid the awkwardness entirely",
    "Protecting their dignity is the read — quiet and quick beats generous and public. If you picked A, watch for that volume next shift — a public announcement turns an inconvenience into a humiliation.",
  ],
  [
    "A guest orders for their whole family but keeps glancing at a crying toddler in the stroller.",
    "Continue at normal pace, the crying isn't your problem",
    "Ask them to calm the child before continuing",
    "Speed up the transaction and offer a small distraction item like a straw or sticker for the toddler",
    "Stop the transaction entirely until the child is quiet",
    "Reading the guest's split attention and easing it wins the moment. If you picked A, watch for that flat pace next shift — technically correct service that ignores visible stress still feels cold.",
  ],
  [
    "A guest is on a phone call, gesturing their order without breaking conversation.",
    "Refuse to take the order until they hang up",
    "Interrupt loudly to get their attention",
    "Read their gestures, confirm quietly with a nod, and process the order with minimal disruption",
    "Ignore them until they finish the call, letting the line back up",
    "Working with a guest's reality instead of demanding they change it is the read. If you picked B, watch for that next shift — forcing an interruption creates friction over something you could adapt to.",
  ],
  [
    "Two guests approach together but only one is ordering — the other stands back, visibly not hungry or upset about something.",
    "Address only the ordering guest and ignore the other entirely",
    "Ask the quiet one directly what's wrong",
    "Serve the ordering guest warmly while offering a small, low-pressure acknowledgment to the other, like a nod or water offer",
    "Comment on the tension between them",
    "A light, non-invasive acknowledgment reads the room without overstepping. If you picked D, watch for that instinct — naming tension you noticed can embarrass guests more than it helps.",
  ],
];

const M1_CASUAL: Row[] = [
  [
    "A table of four is animatedly celebrating something — balloons aren't ordered but the energy is obvious.",
    "Serve them exactly like any other table, no acknowledgment",
    "Ask loudly in front of the whole restaurant what they're celebrating",
    "Warmly ask what's being celebrated when you greet the table, then tailor small touches (a candle, a mention on the check) accordingly",
    "Assume it's a birthday and start singing without confirming",
    "Confirming before acting avoids an awkward wrong guess while still catching the vibe. If you picked D, watch for that next shift — assuming the occasion can embarrass a table celebrating something else entirely.",
  ],
  [
    "A table keeps checking the time and glancing toward the door — they mentioned a show earlier but haven't said anything since.",
    "Continue standard pacing, they'll ask if they need something",
    "Rush their food out without telling them why",
    "Check in and mention you noticed the time, offering to fire their entrees now if that helps",
    "Tell them they should have ordered faster if they're in a rush",
    "Naming the read and offering a fix respects both their time and their comfort. If you picked A, watch for that passivity next shift — visible cues are a request even when no one says the words.",
  ],
  [
    "A solo diner is scrolling their phone but keeps looking up whenever staff pass by.",
    "Leave them alone completely since they're on their phone",
    "Hover near the table making them feel watched",
    "Check in briefly with a genuine, low-pressure question to see if they want conversation or space",
    "Assume they want to be left alone the whole meal without checking",
    "A brief, genuine check-in lets the guest set the tone instead of you guessing wrong in either direction. If you picked D, watch for that next shift — 'obviously wants to be alone' is often just a guess.",
  ],
  [
    "A couple's body language has shifted from relaxed to tense mid-meal — shorter answers, less eye contact between them.",
    "Ask directly if everything is okay between them",
    "Ignore it completely and proceed with standard service",
    "Give them a bit more space between check-ins while remaining warmly available if they need anything",
    "Comp a dessert to try to fix the mood",
    "Reading tension means adjusting your presence, not solving their relationship. If you picked A, watch for that overreach — some reads call for less involvement, not more.",
  ],
  [
    "A family with young kids is visibly frazzled — dropped napkins, a spilled drink, a fussy toddler.",
    "Wait for them to ask for help cleaning up",
    "Comment on how much of a handful the kids are",
    "Proactively bring extra napkins, offer a quick cleanup, and keep your tone light and unbothered",
    "Suggest they might be more comfortable eating elsewhere next time",
    "Showing it's no big deal removes the guest's embarrassment. If you picked A, watch for that wait-and-see approach — a frazzled parent rarely has a free hand to flag you down.",
  ],
  [
    "A guest orders a dish, then hesitates and asks a follow-up question in a tone that suggests dietary concern they haven't stated outright.",
    "Answer only the literal question asked",
    "Tell them to just ask if they have an allergy",
    "Gently probe further — 'is there something specific you're avoiding? I want to make sure it works for you' — to surface the real concern",
    "Recommend they order something else entirely without more information",
    "Reading the hesitation behind the question uncovers the real need. If you picked A, watch for that literalism next shift — guests often signal concerns indirectly before stating them directly.",
  ],
  [
    "Two guests at a shared table have very different energy — one is chatty and warm, the other short and closed-off.",
    "Match your energy equally to both regardless of their signals",
    "Focus your attention mainly on the chatty guest since they're easier",
    "Read each guest individually and adjust your tone person-to-person while keeping table service seamless",
    "Ask the quiet guest directly why they seem unhappy",
    "Table reads aren't uniform — individuals within a table need individual reads. If you picked A, watch for that flattening next shift — one-size energy misses half the table.",
  ],
  [
    "A guest orders wine, sips it, and makes a subtle face before saying nothing.",
    "Assume everything's fine since they didn't complain",
    "Ask if there's a problem in a challenging tone",
    "Circle back within a minute or two and ask directly, giving them an easy opening to say something",
    "Immediately replace the drink without asking first",
    "Giving guests a low-stakes opening to speak up catches issues before they harden into resentment. If you picked A, watch for that assumption next shift — silence at a shared table often isn't agreement.",
  ],
  [
    "A regular's usual server is off tonight, and they seem visibly less at ease with someone new.",
    "Serve exactly the same as any new guest with no adjustment",
    "Apologize repeatedly for not being their usual server",
    "Acknowledge you know their usual order/preferences if you can, and reassure them you've got it covered",
    "Ask them to just wait for their regular server to be available",
    "Showing continuity of care, even from a different face, keeps a regular's comfort intact. If you picked A, watch for that flatness next shift — familiarity is part of what regulars are paying for.",
  ],
  [
    "A table's conversation has gone quiet and they keep looking toward the kitchen — their food is a few minutes past the usual wait.",
    "Say nothing until they ask, sticking to standard timing",
    "Blame the kitchen out loud in front of the table",
    "Proactively update them on timing before they have to ask, with a specific estimate",
    "Offer a full comp before they've even expressed concern",
    "A proactive, specific update turns anxious silence into patience. If you picked A, watch for that wait-it-out instinct — the table's silence is often the guest already deciding whether to complain.",
  ],
];

const M1_FINE: Row[] = [
  [
    "A couple is seated at a table for two, holding hands, clearly on a first date, and glancing around nervously.",
    "Approach with standard, thorough menu explanations at normal length",
    "Comment directly that it looks like a first date",
    "Read the cue and keep interactions warm but efficient, giving them privacy without being absent",
    "Check in more frequently than usual to make sure everything is perfect",
    "Anticipating the need for space is itself the service. If you picked D, watch for that instinct next shift — extra attention on a first date can feel like surveillance, not care.",
  ],
  [
    "A solo diner at the bar orders a full tasting menu and seems to be marking a personal occasion, though they haven't said so.",
    "Treat the meal exactly like any weeknight solo diner",
    "Ask directly what they're celebrating",
    "Offer a small, unprompted gesture — a plating note, a slightly elevated pour — without requiring them to explain themselves",
    "Suggest they might enjoy the meal more with company",
    "Reading the occasion without demanding an explanation lets the guest feel seen on their own terms. If you picked B, watch for that directness next shift — some guests dining solo prefer their reasons stay private.",
  ],
  [
    "A guest's wine glass has been empty for several minutes, but they're deep in conversation and haven't signaled.",
    "Wait for them to explicitly ask for a refill",
    "Interrupt their conversation to ask if they want more wine",
    "Refill unobtrusively without breaking their conversation's flow",
    "Remove the glass assuming they're finished",
    "Anticipating the need without interrupting is the entire craft of silent service. If you picked A, watch for that passivity next shift — an empty glass is itself the signal in fine dining.",
  ],
  [
    "A guest's expression shifts subtly when a dish is set down — not disgust, just a flicker of hesitation.",
    "Say nothing and move on to the next table",
    "Ask bluntly if something's wrong with the dish",
    "Pause briefly nearby and offer a light, low-pressure opening — 'let me know how that lands for you' — without hovering",
    "Immediately offer to remake the dish before they've said anything",
    "A light opening lets the guest choose whether to engage, without presuming a problem exists. If you picked D, watch for that overcorrection — assuming failure before feedback undercuts the guest's own read of the dish.",
  ],
  [
    "A guest requests a table change mid-seating, citing a draft, though their tone suggests something else is bothering them.",
    "Move them without further engagement, treating it as purely about the draft",
    "Question their reasoning before agreeing to move them",
    "Accommodate the request warmly while staying attentive for any further cues about what's really going on",
    "Offer them a discount to compensate for the inconvenience unprompted",
    "Taking the stated reason at face value while staying alert to the real one respects the guest's privacy. If you picked D, watch for that leap next shift — comping before understanding the actual issue can feel presumptuous.",
  ],
  [
    "A regular VIP's usual seating preference is unavailable tonight due to a private event.",
    "Seat them wherever is available with no explanation",
    "Apologize excessively for several minutes before seating them",
    "Proactively explain the situation before they notice, and offer the next-best comparable option with confidence",
    "Ask them to come back another night instead",
    "Getting ahead of the disappointment with a confident alternative preserves the relationship. If you picked A, watch for that silence next shift — VIPs notice a downgrade in seating immediately, explained or not.",
  ],
  [
    "A guest at a business dinner is clearly trying to impress a colleague but fumbles a wine pronunciation.",
    "Correct their pronunciation in front of their guest",
    "Ignore the moment entirely and proceed",
    "Smoothly proceed without drawing attention to the mispronunciation, preserving their credibility",
    "Repeat the correct pronunciation loudly to make sure they learn it",
    "Protecting a guest's social standing in front of their own guest is a form of hospitality. If you picked A, watch for that instinct — correcting a guest publicly serves your ego, not their evening.",
  ],
  [
    "A guest's phone rings during a quiet course and they look mortified as they silence it.",
    "Make eye contact and let the awkwardness sit for a moment",
    "Comment on the interruption to lighten the mood",
    "Continue service smoothly as if nothing happened, giving them room to recover",
    "Pause all service at the table until they've fully recovered",
    "Letting a small embarrassment pass without commentary is a kindness. If you picked D, watch for that overcorrection — stopping service draws more attention to the moment than the phone call did.",
  ],
  [
    "Two guests are dining together but clearly negotiating something tense — quiet voices, careful word choice.",
    "Check in with normal frequency regardless of the tension",
    "Ask if everything is alright in a way that draws attention",
    "Reduce check-in frequency slightly and keep service quiet and efficient, staying available without intruding",
    "Avoid the table entirely to give them full privacy",
    "Calibrating presence — less, but not absent — reads sensitive situations correctly. If you picked D, watch for that swing next shift — full avoidance can leave a table feeling forgotten mid-negotiation.",
  ],
  [
    "A guest orders the same dish as last visit but modifies it slightly, seeming a bit self-conscious about the change.",
    "Question why they're changing their usual order",
    "Process the modification with no acknowledgment of their history",
    "Note the modification warmly, showing you remember their usual without making the change feel like a big deal",
    "Suggest they stick with what they had before",
    "Showing memory without pressure make regulars feel known, not tracked. If you picked A, watch for that framing next shift — questioning a guest's choice undercuts the ease that keeps them coming back.",
  ],
];

// ---------------------------------------------------------------------------
// MODULE 2 — THE RECOVERY PLAY (Decisiveness Under Pressure · Stress Tolerance · Adaptability)
// ---------------------------------------------------------------------------

const M2_QSR: Row[] = [
  [
    "An item just got 86'd mid-rush. The next guest in line is already ordering it.",
    "Apologize repeatedly and let the guest decide on their own",
    "Tell them it's unavailable and wait for their response",
    "Redirect them to a close alternative in the same breath, no hesitation",
    "Offer a free item as compensation before they've even reacted",
    "A same-breath pivot keeps the line moving and doesn't let the guest dwell on the letdown. If you picked A, watch for the apology spiral next shift — it backs up the line and doesn't actually solve anything.",
  ],
  [
    "The POS freezes for a few seconds with five guests waiting in line.",
    "Stand still and wait anxiously for it to come back online",
    "Loudly announce the system is broken to the whole line",
    "Calmly tell the line there's a brief delay, start taking orders on paper if needed, and keep moving",
    "Send everyone to a different register without warning",
    "A calm, immediate workaround keeps trust intact even when tech fails. If you picked A, watch for that freeze next shift — visible panic from staff spreads faster than any system outage.",
  ],
  [
    "A guest's order comes back from the kitchen wrong during a packed rush.",
    "Send it back and make the guest wait through the full queue again",
    "Give them the wrong item anyway to save time",
    "Apologize briefly, flag it for immediate remake priority, and give a clear timeframe",
    "Offer a refund instead of trying to fix the order",
    "A clear fix-it plan with a timeframe turns a mistake into a manageable wait. If you picked A, watch for that default queue-reset next shift — it punishes the guest for a kitchen error.",
  ],
  [
    "Two registers are down at once during the lunch rush and the line is growing fast.",
    "Let the line grow while waiting for IT support",
    "Panic visibly in front of guests",
    "Redirect guests to open registers immediately and communicate the wait clearly",
    "Close the store temporarily until systems are fixed",
    "Fast redistribution keeps the operation moving despite the failure. If you picked A, watch for that passivity — a growing line without communication turns confusion into anger.",
  ],
  [
    "A large mobile order comes in right as the lobby fills with walk-in guests.",
    "Prioritize the mobile order exactly on schedule regardless of the lobby",
    "Ignore the mobile order until the lobby clears",
    "Quickly assess and rebalance priority between mobile and lobby based on real wait times, communicating with both",
    "Cancel the mobile order to focus on the lobby",
    "Reading both queues and rebalancing in real time is decisiveness in action. If you picked A or B, watch for that rigidity next shift — sticking to one queue's schedule ignores the other guest's experience.",
  ],
  [
    "A guest hands you an expired coupon during a rush and the line behind them is getting impatient.",
    "Refuse it outright and move to the next guest",
    "Spend several minutes explaining the policy in detail",
    "Make a quick, reasonable call — honor it or offer an alternative — and move on without dwelling",
    "Call a manager and make the whole line wait for a decision",
    "A fast, reasonable call keeps the line moving without punishing the guest for an honest mistake. If you picked D, watch for that escalation reflex — most coupon calls don't need a manager.",
  ],
  [
    "The fryer goes down and three menu items are suddenly unavailable during peak hours.",
    "Wait for a manager before telling any guests",
    "Let each cashier improvise their own explanation inconsistently",
    "Get a unified 86 announcement out to the team immediately so every register redirects guests the same way",
    "Shut down all ordering until the fryer is fixed",
    "Speed and consistency together prevent the same problem from creating multiple guest experiences. If you picked B, watch for that inconsistency next shift — guests compare notes, and mixed messaging looks unprofessional.",
  ],
  [
    "A guest is visibly frustrated that their order is taking longer than the posted wait time.",
    "Tell them the posted time is just an estimate and walk away",
    "Ignore their frustration and continue at the same pace",
    "Acknowledge the wait directly, give a real update, and visibly prioritize getting their order out",
    "Offer a full refund immediately without checking on the order first",
    "Direct acknowledgment plus real action beats both defensiveness and overcorrection. If you picked D, watch for that reflex next shift — refunding before checking status skips a step that might not be needed.",
  ],
  [
    "A new hire freezes at the register when a guest asks a menu question they don't know the answer to.",
    "Let them keep struggling to figure it out themselves",
    "Take over the register completely without involving them",
    "Step in briefly to answer the guest, then coach the new hire on it right after, keeping the line moving",
    "Send the guest to another register",
    "Solving the immediate problem while still developing the new hire covers both the guest and the team. If you picked B, watch for that instinct next shift — fully taking over skips a coaching moment.",
  ],
  [
    "A large group orders right as a shift change is happening, leaving the floor short-staffed for a few minutes.",
    "Let the incoming shift start cold without a handoff",
    "Delay the group's order until the shift change is fully done",
    "Quickly redistribute tasks across both outgoing and incoming staff to cover the gap without delay",
    "Cancel breaks for the incoming shift to compensate",
    "A fast redistribution bridges the gap without making the guest or the team absorb the cost. If you picked B, watch for that stall next shift — making guests wait for an internal scheduling issue reads as poor planning.",
  ],
];

const M2_CASUAL: Row[] = [
  [
    "Kitchen's backed up, a table's ticket time is creeping past standard — server manages the table's expectations before they ask, buys time with a genuine touch, not an excuse.",
    "Wait until the table asks about the delay",
    "Blame the kitchen directly when the table finally asks",
    "Proactively update the table before they notice, with a specific timeframe and a small gesture like a bread refill",
    "Comp the whole meal immediately to preempt any complaint",
    "Getting ahead of the delay with honesty and a small gesture buys real patience. If you picked A, watch for that wait-and-see approach — tables that have to ask first are already annoyed by the time they do.",
  ],
  [
    "A table's entrees come out and one dish is missing.",
    "Serve the rest and wait for the table to notice the gap",
    "Apologize at length before doing anything to fix it",
    "Immediately flag the kitchen, tell the table it's coming right up, and keep the rest of the table's meal moving",
    "Offer to remake the entire table's order from scratch",
    "Fast, clear communication plus immediate action prevents an annoyance from becoming a complaint. If you picked A, watch for that gap next shift — letting the guest discover the miss themselves reads as inattentive.",
  ],
  [
    "A guest sends back a dish they say is undercooked, and the kitchen is slammed.",
    "Tell the guest the kitchen is busy and it'll take extra time",
    "Argue that the dish looked fine when it left the kitchen",
    "Apologize, flag it as priority with the kitchen, and check back with a real timeframe",
    "Offer a refund on the dish without attempting to fix it first",
    "Prioritizing the fix while managing the wait keeps the guest's trust intact. If you picked D, watch for that reflex — jumping to a refund before offering to make it right can read as giving up on the meal.",
  ],
  [
    "A large party's reservation shows up 20 minutes early while their table is still occupied.",
    "Tell them flatly to wait outside until the table is ready",
    "Rush the current table to leave immediately",
    "Offer the early party a comfortable wait area or the bar, with a clear and honest time estimate",
    "Seat them at a smaller table that doesn't fit the party",
    "Managing both parties' experience with honesty avoids rushing anyone. If you picked B, watch for that pressure tactic — rushing a paying table to accommodate another guest's early arrival isn't fair to either.",
  ],
  [
    "The restaurant loses power for a few minutes during dinner service.",
    "Wait silently in the dark for power to return",
    "Tell guests to leave immediately",
    "Reassure guests calmly, light candles or use phone flashlights if needed, and keep communicating updates",
    "Offer to comp every table in the restaurant immediately",
    "Calm, proactive communication turns a disruption into a manageable moment. If you picked D, watch for that overcorrection — blanket comps before assessing the actual impact on each table isn't necessary.",
  ],
  [
    "A server realizes mid-shift they forgot to put in an appetizer order 15 minutes ago.",
    "Say nothing and hope the table doesn't notice",
    "Blame the kitchen when the table asks about it",
    "Own the mistake immediately, alert the kitchen, and update the table honestly with a fix",
    "Comp the appetizer without telling the table what happened",
    "Owning it immediately, honestly, keeps the table informed and prevents a bigger surprise later. If you picked A, watch for that avoidance — hoping a mistake goes unnoticed rarely works and erodes trust when it surfaces.",
  ],
  [
    "A table complains loudly enough that nearby tables can hear.",
    "Let the conversation continue at the table to avoid drawing more attention",
    "Match their volume to assert control of the situation",
    "Lower your own voice, invite them to a quieter conversation, and address the issue calmly and privately",
    "Ask them to leave immediately",
    "De-escalating volume and moving the conversation protects both the table and the room. If you picked A, watch for that passivity — letting a loud complaint continue publicly affects every guest nearby.",
  ],
  [
    "A guest's credit card is declined at the end of a large group meal.",
    "Announce the decline to the whole table",
    "Assume it's fraud and refuse further attempts",
    "Discreetly inform the guest and offer alternative payment options privately",
    "Ask the whole table to chip in to cover it on the spot",
    "Discretion protects the guest's dignity while still resolving the issue. If you picked A, watch for that public approach next shift — payment issues are private, even in a group setting.",
  ],
  [
    "A to-go order is picked up by the wrong customer due to a mix-up at the counter.",
    "Assume it'll sort itself out and move on",
    "Blame the guest for not checking their bag",
    "Immediately own the mix-up, contact both guests if possible, and prioritize remaking the correct orders",
    "Refuse to remake anything until the original bag is returned",
    "Fast ownership and a remake plan resolve the mistake without punishing either guest. If you picked D, watch for that rigidity — holding a solution hostage to a returned bag delays a fix that's on you to begin with.",
  ],
  [
    "A guest's reservation was lost in the system and the restaurant is fully booked.",
    "Tell them there's nothing that can be done",
    "Blame the reservation system in front of the guest",
    "Apologize sincerely, actively work to find a solution (bar seating, slight wait with a drink on the house), and stay engaged until resolved",
    "Send them away to try another restaurant",
    "Active problem-solving under pressure, not just apology, is what recovers the guest's evening. If you picked A, watch for that shutdown next shift — 'nothing can be done' is rarely actually true.",
  ],
];

const M2_FINE: Row[] = [
  [
    "A course comes back wrong from the kitchen — the recovery has to be seamless enough that the guest never feels the kitchen made a mistake.",
    "Explain in detail what went wrong in the kitchen",
    "Serve it anyway and hope they don't notice",
    "Calmly retrieve the dish, apologize briefly without over-explaining, and ensure the replacement arrives with composed timing",
    "Offer the entire meal free immediately without addressing the dish itself",
    "Composure and quiet correction preserve the evening's tone. If you picked A, watch for that instinct next shift — narrating kitchen mistakes breaks the illusion of seamless service that fine dining depends on.",
  ],
  [
    "A guest's wine order is confirmed but the bottle turns out to be out of stock once opened at the table.",
    "Apologize and offer no immediate solution",
    "Blame inventory management in front of the guest",
    "Smoothly offer a comparable alternative at the same or better value without dwelling on the error",
    "Insist they choose from the full list again from scratch",
    "A smooth, immediate alternative keeps the pacing and tone of the meal intact. If you picked D, watch for that reset next shift — sending a guest back to the full list turns a small hiccup into a bigger interruption.",
  ],
  [
    "A VIP guest's known allergy wasn't properly communicated to the kitchen and the dish arrives at risk.",
    "Serve it and hope the guest catches the issue themselves",
    "Quietly swap the dish without telling the guest what happened",
    "Immediately intercept the dish before service, inform the guest discreetly, and expedite a safe replacement",
    "Cancel the guest's course entirely without offering a replacement",
    "Immediate interception plus honest, discreet communication protects the guest's safety and trust. If you picked A, watch for that risk next shift — safety issues are never something to leave to chance.",
  ],
  [
    "A power flicker briefly dims the dining room during a tasting menu service.",
    "Stop service completely until you're sure it won't happen again",
    "Make a joke about it loudly to the whole room",
    "Continue service smoothly, reassuring nearby tables quietly if needed, without breaking the room's rhythm",
    "Offer every table a complimentary course regardless of whether they noticed",
    "Maintaining rhythm without overreacting keeps composure at the center of the room. If you picked D, watch for that overcorrection — broad comps for a moment most guests won't remember can look performative.",
  ],
  [
    "A guest at a milestone dinner receives the wrong celebratory dessert due to a kitchen mix-up.",
    "Serve it as-is since it's still a dessert",
    "Explain the kitchen error in detail to the guest",
    "Quietly replace it with the correct dessert as fast as possible while keeping the celebratory moment intact",
    "Offer to comp the entire dinner without addressing the dessert itself",
    "Fixing it fast while protecting the moment's meaning matters more than the comp. If you picked B, watch for that instinct next shift — explaining the kitchen's mistake shifts focus away from the guest's celebration.",
  ],
  [
    "A captain notices a table's pacing has fallen behind due to a kitchen delay on the main course.",
    "Wait for the table to ask about the delay",
    "Rush the next course out of sequence to compensate",
    "Proactively inform the table with a specific timeframe and adjust pacing smoothly without rushing",
    "Send an extra amuse-bouche without any explanation",
    "Proactive, specific communication maintains trust without disrupting the meal's structure. If you picked B, watch for that instinct — reordering courses to compensate can create more confusion than the original delay.",
  ],
  [
    "A guest's reserved private dining room has a lingering issue from the prior event (wrong table setting, leftover decor).",
    "Seat them anyway and address it after they notice",
    "Apologize repeatedly without fixing anything immediately",
    "Resolve the issue swiftly before the guest enters, or delay entry by a minute with a smooth explanation",
    "Move the entire party to a different, lesser room without explanation",
    "Fixing it before the guest experiences it is the highest form of the recovery play — invisible correction. If you picked A, watch for that visibility next shift — letting a guest discover an unready room undercuts the room's whole purpose.",
  ],
  [
    "A sommelier realizes mid-pour that the wine is slightly off (corked) after already pouring for the host to taste.",
    "Continue pouring for the rest of the table regardless",
    "Argue with the host about whether it's actually corked",
    "Immediately acknowledge it, apologize once, and swiftly bring a replacement bottle without fuss",
    "Offer the whole table a different wine category entirely without addressing the original bottle",
    "Quick acknowledgment and correction, without argument, keeps the ritual of the tasting intact. If you picked A, watch for that momentum next shift — continuing to pour a flawed bottle undermines the sommelier's credibility.",
  ],
  [
    "A large private event's timeline slips due to a kitchen bottleneck, risking the host's planned toast timing.",
    "Let the timeline slip without informing the host",
    "Tell the host bluntly that the kitchen is behind",
    "Proactively adjust the service sequence and quietly inform the host of a small timing tweak that protects their toast",
    "Cancel the toast portion of the event to save time",
    "Protecting the moment that matters most to the host, even by adjusting behind the scenes, is decisiveness in service of the guest's goals. If you picked A, watch for that silence — a host blindsided by timing has no chance to adjust their own plans.",
  ],
  [
    "A guest disputes the bill at the end of a tasting menu, questioning a specific course's supplement charge.",
    "Insist the charge is correct and end the conversation",
    "Immediately remove the charge without any discussion",
    "Calmly walk through what the charge covers, and use judgment on whether to adjust based on the specific situation",
    "Call over increasingly senior staff until someone agrees to remove it",
    "A calm, informed explanation paired with real judgment resolves most disputes without escalation or reflexive concession. If you picked D, watch for that escalation chain next shift — bouncing the guest between staff signals no one is empowered to make the call.",
  ],
];

// ---------------------------------------------------------------------------
// MODULE 3 — THE HANDOFF (Delegation & Accountability · Teamwork · Time Management)
// ---------------------------------------------------------------------------

const M3_QSR: Row[] = [
  [
    "A server and busser need to turn a table quickly, but no one has clearly said who resets what.",
    "The server does the whole reset alone to avoid confusion",
    "Both wait for a manager to assign the reset",
    "Server and busser split the reset by pre-agreed roles and move immediately",
    "Server resets the table fully and re-does the busser's usual tasks too, 'just in case'",
    "Clear, pre-agreed ownership turns a table reset into a rehearsed two-person unit instead of a negotiation. If you picked A, watch for that pattern next shift — solo-carrying tasks that should be shared burns out your best people fastest.",
  ],
  [
    "A new cashier makes a small cash-count error at the end of their shift.",
    "Take over their drawer counting permanently going forward",
    "Ignore the error since it was small",
    "Review the count together, coach on the specific miss, and let them recount solo next time",
    "Publicly point out the error in front of other staff",
    "Coaching in the moment while returning ownership builds the trust ladder. If you picked A, watch for that instinct — permanently taking over a task after one mistake teaches learned helplessness, not accuracy.",
  ],
  [
    "A shift lead notices a cashier consistently handles register accuracy well over several shifts.",
    "Keep double-checking their drawer anyway, just to be safe",
    "Say nothing and just continue as normal",
    "Formally hand off full ownership of their drawer counts, checking results rather than process",
    "Give them additional unrelated tasks without discussing the shift in responsibility",
    "Recognizing consistency with real trust — not just praise — is what delegation looks like in practice. If you picked A, watch for that habit next shift — continuing to double-check earned trust signals you don't actually believe your own read.",
  ],
  [
    "Two cashiers are unsure who should restock the condiment station during a lull.",
    "Let it go unrestocked until someone is told to do it",
    "One cashier does it every time to avoid the conversation",
    "Quickly agree on a simple rotation or trigger (e.g., whoever notices first) and follow it",
    "Escalate the question to a manager for a permanent policy",
    "A quick, simple agreement beats waiting for a formal policy on a low-stakes task. If you picked D, watch for that over-escalation next shift — not every gap needs a manager-level decision.",
  ],
  [
    "A shift lead is out sick and a senior cashier is asked to informally cover leadership for the shift.",
    "Refuse extra responsibility without formal title or pay clarity in the moment",
    "Take over everything the shift lead normally does, including tasks outside urgent need",
    "Step up to cover the essential leadership gaps for the shift while flagging the pay/title conversation for after service",
    "Let the shift run without anyone actively leading",
    "Covering what's essential now while handling the fairness conversation later keeps the shift running without ignoring the real ask. If you picked D, watch for that vacuum next shift — an unled shift creates more problems than an imperfect stand-in.",
  ],
  [
    "A cashier delegates a task to a newer team member but doesn't check on it again until the end of the shift.",
    "This is fine — delegation means fully hands-off",
    "Redo the task yourself without telling them, just in case",
    "Check in briefly partway through to catch issues early, without micromanaging the whole process",
    "Stand over their shoulder for the entire task",
    "A light mid-point check balances trust with accountability. If you picked A, watch for that gap next shift — full hands-off with zero check-in isn't delegation, it's absence.",
  ],
  [
    "A lead needs to decide whether a three-shift-clean cashier is ready to train new hires themselves.",
    "Wait for a much longer track record before considering it",
    "Assign it without any conversation about what training well looks like",
    "Promote them to training duty with a short conversation on what good training looks like, then observe their first session",
    "Never delegate training, keep it exclusively with leads",
    "Combining promotion with a quick calibration conversation sets the new trainer up to succeed. If you picked D, watch for that bottleneck — leads who never delegate training cap how fast the team can grow.",
  ],
  [
    "Two team members disagree about who was supposed to handle closing duties.",
    "Assign blame to whoever complains loudest",
    "Let it go unresolved to avoid conflict",
    "Clarify ownership going forward with both present, focusing on the fix rather than blame",
    "Take over closing duties yourself from now on to avoid the conflict recurring",
    "A forward-focused clarification prevents the same ambiguity from repeating without punishing either person. If you picked D, watch for that overcorrection — absorbing the task yourself removes accountability instead of establishing it.",
  ],
  [
    "A cashier wants more responsibility but hasn't yet shown consistency in their current role.",
    "Give them the new responsibility immediately to keep them motivated",
    "Tell them no without any path forward",
    "Acknowledge the interest, define what consistency would look like, and set a real timeline to revisit it",
    "Ignore the request entirely",
    "Pairing the 'no, not yet' with a clear path keeps ambition alive instead of shutting it down. If you picked B, watch for that flat rejection next shift — motivated people who hit a wall with no path often disengage.",
  ],
  [
    "A shift lead is buried in a rush and a capable team member offers to take over a specific task without being asked.",
    "Decline the help to keep control of every task yourself",
    "Accept but then hover and re-check everything they do",
    "Accept the offer and trust them to run with it, checking results afterward",
    "Accept but hand them a completely different, unrelated task instead",
    "Accepting real help and trusting the follow-through is delegation in its simplest form. If you picked A, watch for that reflex next shift — declining help during a rush to maintain control usually just extends the rush.",
  ],
];

const M3_CASUAL: Row[] = [
  [
    "Captain delegates full course choreography to a server team, stepping back to observe — intervening only if timing or standard slips, not to micromanage every plate.",
    "Direct every plate placement personally throughout service",
    "Step back completely and never check in during service",
    "Observe from a distance and step in only if timing or standard actually slips",
    "Assign the choreography once and never revisit it even as issues arise",
    "Trusting the team while staying alert for real slippage is the balance point of delegation. If you picked A, watch for that instinct — directing every plate defeats the purpose of building a team that can run itself.",
  ],
  [
    "A server trainee is shadowing a senior server during a moderate rush.",
    "Have the trainee just watch silently the entire shift",
    "Throw the trainee into full independent service immediately",
    "Give the trainee small, real tasks with clear guidance, increasing responsibility as they show readiness",
    "Have the senior server do everything while narrating from across the room",
    "Graduated, real responsibility builds competence faster than pure observation or a sink-or-swim approach. If you picked A, watch for that passivity next shift — watching without doing rarely transfers into actual skill.",
  ],
  [
    "Two servers need to cover each other's sections during a bathroom break.",
    "Let the section go completely uncovered for a few minutes",
    "Have the covering server ignore the other section's needs until the break ends",
    "Quickly agree on what needs monitoring and hand off key details before stepping away",
    "Require a manager to formally approve every bathroom break coverage",
    "A quick, specific handoff keeps both sections covered without needing management involvement. If you picked D, watch for that bottleneck next shift — routine coverage shouldn't require manager sign-off every time.",
  ],
  [
    "A manager notices a server consistently handles difficult tables well.",
    "Keep assigning them only easy tables to reduce their stress",
    "Say nothing and continue as normal",
    "Start trusting them with more of the challenging tables and eventually mentorship of newer staff",
    "Publicly praise them without giving any additional responsibility",
    "Matching real trust to demonstrated skill is what growing a team looks like. If you picked A, watch for that protectiveness next shift — shielding strong performers from challenge actually limits their growth.",
  ],
  [
    "A large party needs multiple servers working in coordination without a captain present.",
    "Have each server work their own tables within the party independently, without coordination",
    "Wait for a manager to assign specific roles before starting service",
    "Have the team quickly self-organize roles (drinks, apps, mains) before service begins",
    "Assign one server to handle the entire large party alone",
    "Fast self-organization before service starts prevents the chaos of uncoordinated independent service. If you picked A, watch for that fragmentation next shift — servers working a shared party without coordination creates a disjointed guest experience.",
  ],
  [
    "A busser consistently finishes their side work early and has downtime.",
    "Let them stand idle until their shift ends",
    "Pile on random extra tasks without explanation",
    "Give them a clear, valued task (like proactively supporting a busy section) that uses the downtime well",
    "Send them home early every time this happens",
    "Purposeful downtime use turns idle time into real value without feeling like busywork. If you picked B, watch for that randomness next shift — tasks without explanation feel like punishment for being efficient.",
  ],
  [
    "A server disagrees with how a manager delegated a task during a busy shift.",
    "Argue about it in front of guests or other staff",
    "Silently comply while resenting the decision",
    "Comply in the moment, then raise the disagreement privately after the shift",
    "Ignore the delegation and do the task their own way instead",
    "Executing in the moment while addressing disagreement later protects the shift and the relationship. If you picked D, watch for that override next shift — silently doing it your own way undermines the whole point of delegation.",
  ],
  [
    "A manager wants to delegate the weekly schedule-building task to a senior server for the first time.",
    "Hand it off completely with zero guidance on constraints",
    "Keep doing it themselves indefinitely to avoid any risk",
    "Walk through the key constraints once, then let them build it and review the first draft together",
    "Have them build it, then rebuild it entirely without saying what changed",
    "A guided first attempt plus real feedback builds the skill faster than either extreme. If you picked D, watch for that pattern next shift — silently redoing someone's work teaches them nothing about what to fix.",
  ],
  [
    "A team member takes initiative on a task outside their normal role during a slow period.",
    "Tell them to stick strictly to their own job description",
    "Let it happen without any acknowledgment either way",
    "Acknowledge the initiative positively and clarify if it's something to continue going forward",
    "Assign it to them permanently without a conversation about whether they want it",
    "Positive acknowledgment plus a real conversation about ownership respects their initiative without assuming too much. If you picked A, watch for that rigidity next shift — shutting down initiative teaches people to stop offering it.",
  ],
  [
    "A server calls out sick last-minute and the remaining team needs to redistribute their section.",
    "Leave the section unassigned until a replacement is found",
    "Assign the entire section to one already-busy server",
    "Quickly split the section across the existing team based on current capacity",
    "Close that section of the restaurant for the shift",
    "Fast, capacity-aware redistribution keeps service running without overloading any one person. If you picked B, watch for that overload next shift — dumping a whole section on one already-busy server sets up a second failure.",
  ],
];

const M3_FINE: Row[] = [
  [
    "A captain is training a new server team member for private dining events.",
    "Have them shadow silently for several full events before any real involvement",
    "Give them a full private event to run solo immediately",
    "Give them a defined, real piece of the event to own with the captain nearby to observe",
    "Have the captain run the entire event without involving the trainee at all",
    "A defined, real slice of ownership with observation nearby builds competence faster than pure shadowing. If you picked A, watch for that extended passivity — long observation periods without real stakes slow down actual skill-building.",
  ],
  [
    "A sommelier delegates a wine pairing recommendation to a junior server for a specific table.",
    "Override every recommendation before it reaches the table",
    "Let any recommendation go to the table with zero review",
    "Briefly review the junior server's reasoning before service, then let them deliver it themselves",
    "Deliver the recommendation personally and have the junior server just observe",
    "A quick review plus real delivery builds the junior server's judgment while protecting the guest experience. If you picked D, watch for that pattern next shift — always delivering it yourself never actually transfers the skill.",
  ],
  [
    "A captain notices a server team member is ready for more responsibility during VIP service.",
    "Wait indefinitely for a 'perfect' moment to give them more responsibility",
    "Give them full VIP ownership immediately without any transition",
    "Gradually increase their role in VIP service, starting with a lower-stakes VIP table",
    "Never expand their role regardless of readiness",
    "A gradual, real increase in stakes matches responsibility to demonstrated readiness. If you picked B, watch for that leap next shift — full VIP ownership without transition risks the guest experience on an untested jump.",
  ],
  [
    "Two servers need to coordinate a complex tableside preparation without the captain present.",
    "Have one server do the entire preparation alone",
    "Wait for the captain before starting despite time pressure",
    "Coordinate roles between themselves quickly based on established training and proceed",
    "Improvise completely without reference to any established process",
    "Falling back on established training to self-coordinate keeps the standard intact without needing a captain for every moment. If you picked B, watch for that dependency next shift — a team that can't proceed without the captain present isn't actually delegated to.",
  ],
  [
    "A captain steps back to observe a server team run a full service independently for the first time.",
    "Intervene on every minor deviation from the usual process",
    "Stay completely uninvolved even if standards clearly slip",
    "Intervene only when timing or standard genuinely slips, otherwise let them run it",
    "Cancel the independent run at the first sign of any issue",
    "Selective intervention — only for real slippage — is what makes an independent run a genuine test and a genuine trust exercise. If you picked A, watch for that instinct next shift — correcting every small deviation defeats the purpose of the independent run.",
  ],
  [
    "A server team member consistently under-delivers on a delegated task despite clear instructions.",
    "Continue delegating the same way indefinitely, hoping it improves",
    "Take the task away permanently without any conversation",
    "Have a direct conversation about the gap, then decide together on adjusted support or expectations",
    "Publicly reassign the task in front of the team without private discussion first",
    "A direct, private conversation addresses the real gap without embarrassing the team member or ignoring the pattern. If you picked D, watch for that public reassignment — it damages trust far beyond the original performance issue.",
  ],
  [
    "A captain needs to decide whether to delegate menu-change communication to the floor team or handle it personally.",
    "Handle every menu change communication personally, indefinitely",
    "Delegate it fully with no briefing on what's changed or why",
    "Brief the floor team clearly on the change and its reasoning, then trust them to communicate it to guests",
    "Post a printed notice and skip verbal communication with the team entirely",
    "A clear briefing plus trusted delegation scales communication without the captain being a bottleneck. If you picked A, watch for that bottleneck next shift — personally handling every change doesn't scale as the team grows.",
  ],
  [
    "A junior team member asks to take on a task typically reserved for senior staff.",
    "Deny the request outright with no explanation",
    "Grant it immediately with no assessment of readiness",
    "Assess their readiness honestly, and if close, create a specific path to get there",
    "Ignore the request and hope they stop asking",
    "Honest assessment plus a real path respects the ambition without compromising the standard. If you picked A, watch for that flat denial next shift — a request with no explanation reads as dismissal, not honesty.",
  ],
  [
    "A captain delegates end-of-night reconciliation to a trusted server for the first time.",
    "Redo the entire reconciliation themselves afterward without saying why",
    "Never check the results at all, treating it as fully hands-off from day one",
    "Review the results together the first few times, then shift to spot-checks as trust builds",
    "Have someone else secretly double-check without the trusted server knowing",
    "A visible, collaborative review period builds real trust faster than either silent redoing or covert double-checking. If you picked D, watch for that secrecy next shift — covert checking erodes trust the moment it's discovered.",
  ],
  [
    "A server team collectively decides how to handle a last-minute large reservation without the captain immediately available.",
    "Wait entirely until the captain can be reached",
    "Have one server unilaterally decide for the whole team",
    "Quickly align as a team on roles based on established standards, then proceed",
    "Turn away the reservation to avoid the coordination problem",
    "Team alignment under pressure, grounded in established standards, is delegation and accountability working together without needing to wait. If you picked D, watch for that avoidance next shift — turning away business to dodge a coordination challenge isn't actually solving anything.",
  ],
];

// ---------------------------------------------------------------------------
// MODULE 4 — THE MESSAGE (Cross-Functional Communication · Conflict Resolution · Coaching)
// ---------------------------------------------------------------------------

const M4_QSR: Row[] = [
  [
    "Cashier flags a recurring complaint pattern up to the lead in one clear sentence during a lull.",
    "Mention it vaguely in passing without specifics",
    "Wait until the end-of-week meeting to bring it up",
    "Give the lead a specific, one-sentence summary of the pattern with enough detail to act on immediately",
    "File a lengthy written report before saying anything verbally",
    "A specific, actionable one-liner in the moment gets faster results than a vague comment or a delayed report. If you picked D, watch for that delay next shift — a pattern worth reporting is usually worth reporting today.",
  ],
  [
    "A lead needs to relay a new corporate policy to the register team quickly before the lunch rush.",
    "Read the entire corporate memo verbatim to the team",
    "Mention it briefly with no explanation of why it matters",
    "Translate the policy into one clear, practical instruction the team can act on immediately",
    "Post the memo on the wall and assume everyone will read it",
    "Translating policy into a practical action is the core of cross-functional communication. If you picked D, watch for that assumption next shift — posted memos rarely get read before a rush actually starts.",
  ],
  [
    "A team member has a great idea for improving the drive-thru flow but is hesitant to share it.",
    "Wait for them to bring it up unprompted",
    "Dismiss ideas from newer team members generally",
    "Actively invite input by asking directly what they've noticed that could work better",
    "Implement ideas only when they come from senior staff",
    "Actively inviting input surfaces good ideas that would otherwise stay unspoken. If you picked A, watch for that passivity next shift — waiting for hesitant team members to volunteer ideas means losing most of them.",
  ],
  [
    "A cashier needs to escalate a guest complaint about food quality to a manager who's currently on a call.",
    "Interrupt the call immediately regardless of urgency",
    "Wait until the manager is completely free, even if it takes a while",
    "Signal the urgency level clearly and get a quick decision without demanding a full interruption",
    "Handle the complaint alone without any manager involvement",
    "Communicating urgency without demanding a full interruption respects both the guest's timeline and the manager's. If you picked B, watch for that delay next shift — some complaints genuinely can't wait for a call to end.",
  ],
  [
    "A new team member is repeatedly making the same small mistake at the register.",
    "Let it continue since it's a minor issue",
    "Correct them the same generic way every time without additional detail",
    "Give specific, in-the-moment coaching tied to exactly what went wrong and how to fix it",
    "Write them up formally without any prior coaching conversation",
    "Specific, timely coaching addresses the root cause faster than repetition or formal escalation. If you picked D, watch for that jump next shift — formal write-ups without coaching first skip the step that actually changes behavior.",
  ],
  [
    "Corporate rolls out a new promotion the team hasn't been briefed on, and a guest asks about it.",
    "Tell the guest you don't know anything about it",
    "Make up details to avoid seeming uninformed",
    "Acknowledge you'll find out immediately, get the real answer fast, and follow up with the guest",
    "Tell the guest to look it up online themselves",
    "Owning the gap honestly while moving fast to close it keeps guest trust intact. If you picked B, watch for that improvisation next shift — guessing at promotion details risks giving guests wrong information.",
  ],
  [
    "A lead needs to communicate a schedule change to the team with minimal advance notice.",
    "Post it quietly without a direct conversation with those affected",
    "Wait until the shift starts to mention it",
    "Communicate directly and as early as possible, explaining the reason briefly",
    "Have someone else deliver the news instead of doing it personally",
    "Direct, early, and explained communication respects the team even when the news is short-notice. If you picked D, watch for that avoidance next shift — delegating hard news you should deliver personally damages trust.",
  ],
  [
    "Two team members have a disagreement about register procedure that's affecting their teamwork.",
    "Let them work it out entirely on their own with no involvement",
    "Take one side without hearing both perspectives",
    "Hear both sides briefly, clarify the correct procedure, and move forward without assigning blame",
    "Escalate immediately to upper management without attempting resolution first",
    "Clarifying the actual standard without picking sides resolves the practical issue without deepening the conflict. If you picked D, watch for that escalation reflex next shift — most procedure disagreements can be resolved at the floor level.",
  ],
  [
    "A shift lead notices team morale dipping over several shifts but hasn't identified a clear cause.",
    "Ignore it since there's no specific complaint",
    "Assume it's just normal fluctuation and move on",
    "Ask a few direct, open questions to the team to surface the real cause",
    "Implement a generic morale-boosting activity without investigating first",
    "Asking direct questions to find the actual cause beats guessing at a generic fix. If you picked D, watch for that shortcut next shift — a morale activity aimed at the wrong problem won't move the needle.",
  ],
  [
    "Upper management asks a shift lead for a quick update on how a new process is working on the floor.",
    "Give a vague, general answer to avoid seeming critical",
    "List every minor issue without prioritizing what matters",
    "Give a clear, prioritized summary of what's working and what needs attention",
    "Say everything is fine to avoid a longer conversation",
    "A clear, prioritized summary is what actually helps upper management make decisions. If you picked D, watch for that instinct next shift — smoothing over real issues just delays them resurfacing later, worse.",
  ],
];

const M4_CASUAL: Row[] = [
  [
    "Server and kitchen communicate a modification or allergy clearly enough that it survives being relayed twice before it hits the line.",
    "Mention it verbally once and trust it'll make it to the line",
    "Write it vaguely on the ticket without emphasis",
    "Clearly flag it both verbally and in writing, confirming it registered with whoever's expediting",
    "Assume the kitchen will ask if they need clarification",
    "Double-confirming critical modifications in both verbal and written form is what survives the relay. If you picked A, watch for that assumption next shift — a single verbal mention is the easiest thing to lose in a busy kitchen.",
  ],
  [
    "A manager needs to relay a guest complaint about slow service to the kitchen without assigning blame unfairly.",
    "Tell the kitchen the guest said they're too slow, verbatim",
    "Say nothing to avoid conflict between front and back of house",
    "Share the specific, factual timing issue and ask the kitchen's perspective on what happened",
    "Post a general reminder about speed to the whole kitchen without specifics",
    "Sharing specifics and asking for the kitchen's side gets an actual answer instead of defensiveness. If you picked B, watch for that avoidance next shift — unaddressed complaints tend to repeat.",
  ],
  [
    "A server needs to tell a table their requested modification isn't possible due to kitchen constraints.",
    "Blame the kitchen directly to the table",
    "Say it's just not possible with no explanation",
    "Explain briefly and offer a close alternative that still respects their preference",
    "Ignore the request and hope they don't ask again",
    "A brief explanation plus a real alternative respects the guest without needing to throw the kitchen under the bus. If you picked D, watch for that avoidance next shift — ignoring a stated preference reads as not listening.",
  ],
  [
    "A trainer is coaching a new server on how to handle a guest complaint, using a real example from that same shift.",
    "Wait until the next scheduled review to bring it up",
    "Correct them harshly in front of the guest",
    "Debrief right after the interaction, privately, tying feedback to the specific moment",
    "Let it go without any feedback since the guest wasn't too upset",
    "Immediate, private, specific coaching turns a real moment into real learning. If you picked A, watch for that delay next shift — feedback tied to a specific moment loses its power the longer it waits.",
  ],
  [
    "Front-of-house and back-of-house have different understandings of a new menu item's preparation time.",
    "Let each side keep operating on their own assumption",
    "Have front-of-house dictate the timing to the kitchen unilaterally",
    "Get both sides in a quick conversation to align on the actual timing before service",
    "Avoid the topic since it hasn't caused a problem yet",
    "A quick alignment conversation prevents the mismatch from surfacing mid-service in front of guests. If you picked D, watch for that avoidance next shift — an unaddressed mismatch usually surfaces at the worst possible time.",
  ],
  [
    "A server needs to give upper management honest feedback about a policy that's not working well on the floor.",
    "Say nothing to avoid seeming negative",
    "Complain about it informally to coworkers instead",
    "Raise it directly and constructively with specific examples and a suggested fix",
    "Wait for someone else to bring it up first",
    "Direct, constructive feedback with specifics and a suggestion is what actually changes policy. If you picked B, watch for that pattern next shift — venting to coworkers instead of raising it up never reaches the people who can fix it.",
  ],
  [
    "A manager needs to deliver difficult feedback to a long-tenured server about a recurring issue.",
    "Avoid the conversation because of their tenure",
    "Deliver the feedback publicly during a shift meeting",
    "Have a direct, private, respectful conversation focused on the specific behavior",
    "Have someone else deliver the feedback on their behalf",
    "A direct but respectful private conversation is what tenure actually earns — not avoidance. If you picked A, watch for that hesitation next shift — tenure doesn't make an issue go away on its own.",
  ],
  [
    "A busser notices a recurring issue with how tables are being reset but isn't sure it's their place to say something.",
    "Stay quiet since it's outside their formal role",
    "Complain to other bussers instead of raising it with a manager",
    "Bring it to a manager or lead directly, framed as a helpful observation",
    "Try to fix it unilaterally without telling anyone",
    "Framing an observation helpfully, regardless of formal role, is exactly the kind of floor-to-office translation the team needs. If you picked A, watch for that silence next shift — good observations often come from people who don't feel entitled to share them.",
  ],
  [
    "Two servers have different information about a daily special's ingredients, risking a wrong answer to a guest.",
    "Each server tells guests their own version without checking",
    "Avoid mentioning the special to guests to sidestep the issue",
    "Quickly confirm the correct details with the kitchen before service and align on one answer",
    "Guess based on which version sounds more likely to be correct",
    "A quick confirmation before service prevents guests from getting two different answers to the same question. If you picked D, watch for that guesswork next shift — guessing on ingredient details risks a real allergy issue, not just an inconsistency.",
  ],
  [
    "A shift lead needs to communicate a last-minute staffing shortage to both the team and arriving guests.",
    "Say nothing and let service slow down without explanation",
    "Tell guests the restaurant is simply understaffed with no further context",
    "Brief the team on how to adjust, and give guests a brief, honest heads-up with a service adjustment",
    "Cancel reservations without notice to manage the shortage",
    "Briefing the team while being honest with guests keeps both sides informed and manages expectations. If you picked A, watch for that silence next shift — guests notice slower service regardless; an explanation changes how they feel about it.",
  ],
];

const M4_FINE: Row[] = [
  [
    "Captain translates a VIP guest's unspoken preference into precise, private instruction to the entire team before the guest even sits down.",
    "Mention the preference casually to whichever server is nearby",
    "Wait until the guest is seated to figure out the details",
    "Brief the entire section clearly and privately before the guest sits down, with zero ambiguity",
    "Write a note and leave it in the kitchen without a verbal briefing",
    "A complete, private pre-briefing means the whole team acts in sync from the first moment. If you picked D, watch for that reliance next shift — a written note without verbal confirmation is easy to miss in a busy pass.",
  ],
  [
    "A sommelier needs to communicate a guest's wine preference discovered mid-meal to the kitchen for pairing the next course.",
    "Assume the kitchen will figure it out from the wine choice alone",
    "Wait until the course is already plated to mention it",
    "Communicate the preference clearly and immediately, before the next course is finalized",
    "Handle it entirely independently without involving the kitchen",
    "Immediate, clear communication before the course is finalized lets the kitchen actually act on it. If you picked A, watch for that assumption next shift — inferring intent without stating it plainly risks a mismatch.",
  ],
  [
    "A captain needs to relay a subtle but important complaint from a regular guest to the chef without damaging the relationship.",
    "Relay it exactly as bluntly as the guest said it",
    "Soften it so much that the actual issue gets lost",
    "Relay the substance accurately while framing it constructively for a productive response",
    "Avoid telling the chef at all to keep the peace",
    "Accurate substance with constructive framing gets the issue fixed without damaging the kitchen relationship. If you picked D, watch for that avoidance next shift — an unaddressed regular's complaint tends to resurface, worse.",
  ],
  [
    "A new server on the fine dining floor needs coaching on a subtle service error from that evening.",
    "Wait for the next scheduled formal review",
    "Correct them in front of the guest to fix it immediately",
    "Debrief privately after service, tying the feedback to the specific moment while it's fresh",
    "Let it go since fine dining service is already high-pressure",
    "Timely, private, specific coaching is how fine dining service actually improves shift over shift. If you picked D, watch for that leniency next shift — letting subtle errors go because of pressure just normalizes them.",
  ],
  [
    "The kitchen and front-of-house have different read on how many covers a private event will actually need.",
    "Let each side plan independently based on their own assumption",
    "Have the front-of-house team dictate the number without kitchen input",
    "Get both sides aligned on a single, confirmed number before final prep begins",
    "Avoid finalizing a number until the day of the event",
    "A single confirmed number, agreed by both sides, prevents either over- or under-preparation. If you picked D, watch for that delay next shift — waiting until the day of the event to align leaves no room to adjust.",
  ],
  [
    "A captain needs to explain a significant menu change to the entire floor team before a new tasting menu launches.",
    "Send a written summary with no verbal walkthrough",
    "Explain it once quickly right before service starts",
    "Hold a proper walkthrough well ahead of launch, with time for questions",
    "Let each server learn about it from guests asking questions",
    "A proper walkthrough with time for questions ensures the whole team can represent the new menu with confidence. If you picked D, watch for that gap next shift — learning about a menu change from a guest's question undermines the whole team's credibility.",
  ],
  [
    "A guest at a fine dining restaurant gives feedback that upper management should hear about a recurring pattern.",
    "Keep it at the floor level and never escalate it",
    "Exaggerate it to make sure it gets attention",
    "Escalate it accurately with specific detail and a suggested next step",
    "Wait to see if it happens again before mentioning it",
    "Accurate escalation with a suggested fix is what turns floor-level feedback into an actual improvement. If you picked D, watch for that delay next shift — waiting for a pattern to repeat costs the guests in between.",
  ],
  [
    "Two team members have a quiet disagreement about how to handle a VIP's special request, visible to a nearby captain.",
    "Let them resolve it themselves in front of the guest area",
    "Publicly correct one of them on the spot",
    "Quietly pull them aside, clarify the standard, and resolve it away from guest view",
    "Ignore it since the guest hasn't reacted yet",
    "Resolving it quietly and away from guest view protects the room's atmosphere while still fixing the issue. If you picked A, watch for that visibility next shift — a visible disagreement, even quiet, can be sensed by a perceptive guest.",
  ],
  [
    "A captain needs to give the kitchen real-time feedback about pacing without disrupting the kitchen's flow during service.",
    "Interrupt with lengthy explanations mid-service",
    "Say nothing until service is completely over",
    "Give brief, clear, timely updates that don't require the kitchen to stop and process a long explanation",
    "Have a server relay vague, secondhand impressions instead of specifics",
    "Brief, clear, real-time updates respect the kitchen's flow while still keeping pacing on track. If you picked B, watch for that delay next shift — feedback given after service is over can't fix anything happening tonight.",
  ],
  [
    "A general manager wants an honest assessment from the floor team about whether a new reservation system is working.",
    "Tell the manager it's fine to avoid a longer conversation",
    "List every complaint without any prioritization or context",
    "Give a clear, prioritized, honest assessment with specific examples",
    "Avoid giving an opinion and defer to whatever management already thinks",
    "A clear, prioritized, honest assessment is what actually helps leadership make a good decision. If you picked D, watch for that deference next shift — withholding a real opinion when asked directly wastes the chance to fix something that isn't working.",
  ],
];

export function getAllScenarios(): ScenarioSeed[] {
  return [
    ...build(1, "QSR", "Emotional Intelligence (The Guest Read)", M1_QSR),
    ...build(1, "CASUAL", "Emotional Intelligence (The Guest Read)", M1_CASUAL),
    ...build(1, "FINE_DINING", "Emotional Intelligence (The Guest Read)", M1_FINE),

    ...build(2, "QSR", "Decisiveness Under Pressure (The Recovery Play)", M2_QSR),
    ...build(2, "CASUAL", "Decisiveness Under Pressure (The Recovery Play)", M2_CASUAL),
    ...build(2, "FINE_DINING", "Decisiveness Under Pressure (The Recovery Play)", M2_FINE),

    ...build(3, "QSR", "Delegation & Accountability (The Handoff)", M3_QSR),
    ...build(3, "CASUAL", "Delegation & Accountability (The Handoff)", M3_CASUAL),
    ...build(3, "FINE_DINING", "Delegation & Accountability (The Handoff)", M3_FINE),

    ...build(4, "QSR", "Cross-Functional Communication (The Message)", M4_QSR),
    ...build(4, "CASUAL", "Cross-Functional Communication (The Message)", M4_CASUAL),
    ...build(4, "FINE_DINING", "Cross-Functional Communication (The Message)", M4_FINE),
  ];
}
